server:
  port: 18080
  log:
    path: logs

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )

logging:
  level:
    root: DEBUG

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(ZZPjnmauGH2uvT8X/lI2b63Xi/ttt9bIseRIDIStGBN5VE72VcaGSz3ZpbgkHjdWh3UPQ6knYPimuW22EkH5dd2UysORO5zv23ZceSXiK8POU/TkTBfgIrjDt8v6vDX5)
            client-secret: ENC(zJU12eBp8YiPiZxUeMGxs1TjuB2fRzI4e13pz9Rbxf4OksZllCvJ7GqZU3zunIylyiTucVST1KI=)
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/api/oauth2/{registrationId}/callback"
          kakao:
            authorization-grant-type: authorization_code
            client-id: ENC(6CaE5vNLcgIlDAACsX5P42+zZcC0AvsPtOIxCFREfCSQvQUksQ+ONI5lpIkDJmHIClG1ovMVg6s=)
            client-secret: ENC(rYLBoQoyub3KEmkdw3UhJ+JcdjRhhlSa9ZokHhzhDS9wFUQgl3jRcl6GBhAXLMlHOz2/KRCV4LQ=)
            scope:
              - profile_nickname
            redirect-uri: "{baseUrl}/api/oauth2/{registrationId}/callback"
            client-name: kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-name-attribute: id
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me

file:
  uploaded-path: /Users/bean/Development/bboobbooFiles

jwt:
  atk-expired-time: 1800
  rtk-expired-time: 1209600
