server:
  port: 18080
  log:
    path: logs

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )

logging:
  level:
    root: DEBUG

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB

file:
  uploaded-path: /Users/bean/Development/bboobbooFiles

jwt:
  atk-expired-time: 1800
  rtk-expired-time: 1209600
